// Code generated by traust-contracts codegen. DO NOT EDIT.

package enums

// MitigationEffort — Values of `effort` in threat-model.schema.json.
type MitigationEffort string

const (
	MitigationEffortXS MitigationEffort = "XS"
	MitigationEffortS  MitigationEffort = "S"
	MitigationEffortM  MitigationEffort = "M"
	MitigationEffortL  MitigationEffort = "L"
)

// MitigationEffortValues returns all valid MitigationEffort values.
func MitigationEffortValues() []MitigationEffort {
	return []MitigationEffort{
		MitigationEffortXS,
		MitigationEffortS,
		MitigationEffortM,
		MitigationEffortL,
	}
}
